<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="9.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.15">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.15" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.7" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="QRCoder" Version="1.8.0" />
		<PackageReference Include="QuestPDF" Version="2026.2.4" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Esfsg.Domain\Esfsg.Domain.csproj" />
		<ProjectReference Include="..\Esfsg.Infra.CrossCutting.Data\Esfsg.Infra.Data.csproj" />
	</ItemGroup>

</Project>
