name: Build and deploy ASP.Net Core app to Azure Web App - esfsg-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read 

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 'v8.0'

      - name: Restaurar dependências
        run: dotnet restore ./Esfsg.API/esfsg-backend.sln

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore ./Esfsg.API/esfsg-backend.sln

      - name: dotnet publish
        run: dotnet publish ./Esfsg.API/Esfsg.API/Esfsg.API.csproj --configuration Release --output ./publish

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'esfsg-backend' 
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish

      # ----------------------------
      # BUILD E DEPLOY DO HANGFIRE
      # ----------------------------

      - name: Publish Hangfire
        run: dotnet publish ./Esfsg.API/Esfsg.Hangfire/Esfsg.Hangfire.csproj --configuration Release --output ./publish-hangfire

      - name: Deploy Hangfire para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'esfrsg-hangfire'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_HANGFIRE_PUBLISH_PROFILE }}
          package: ./publish-hangfire
          